version: 2
jobs:
  build:
    docker:
      - image: imrehg/archlinux-makepkg
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: echo 'MAKEFLAGS="-j2"' | sudo tee -a /etc/makepkg.conf
      - run: ./docker-build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build