version: 2
jobs:
  build:
    docker:
      - image: archlinux:latest
    steps:
      - run: |
          pacman -Syy --noconfirm
          pacman --noconfirm -S git
      - checkout
      - run: |
          ls -la
          build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build